"""Product readiness contracts and fail-closed evaluators."""

from .contracts import (
    LUNA_COORDINATOR_REF,
    PRE_BETA_SECURITY_GATE_IDS,
    REQUIRED_SECURITY_GATE_IDS,
    CapabilityEvidence,
    CapabilityResult,
    CapabilityStatus,
    CoordinatorApproval,
    CoordinatorDecision,
    DowngradeResult,
    EvidenceClass,
    LayeredReadinessDecision,
    ReadinessDowngrade,
    ReadinessEvidence,
    ReadinessLevel,
    ReadinessStatus,
    ReadinessTier,
    ReadinessValidationError,
    SecurityGateDecision,
    SupportabilityDecision,
    SupportabilityStatus,
    evidence_class_at_least,
    validate_digest,
    validate_evidence_reference,
    validate_revision,
    validate_scope_segment,
)
from .evaluator import (
    DowngradeStore,
    ReadinessEvaluationError,
    ReadinessEvaluator,
    SupportabilityEvaluator,
)
from .persistence import InMemoryReadinessDowngradeStore, SqlAlchemyReadinessStore
from .registry import (
    MANDATORY_CAPABILITIES,
    ApplicationCapabilityRegistry,
    CapabilityDefinition,
    CapabilityRegistry,
    default_capability_registry,
)

__all__ = [
    "ApplicationCapabilityRegistry",
    "CapabilityDefinition",
    "CapabilityEvidence",
    "CapabilityRegistry",
    "CapabilityResult",
    "CapabilityStatus",
    "CoordinatorApproval",
    "CoordinatorDecision",
    "DowngradeStore",
    "DowngradeResult",
    "EvidenceClass",
    "InMemoryReadinessDowngradeStore",
    "LayeredReadinessDecision",
    "LUNA_COORDINATOR_REF",
    "MANDATORY_CAPABILITIES",
    "PRE_BETA_SECURITY_GATE_IDS",
    "ReadinessDowngrade",
    "ReadinessEvaluationError",
    "ReadinessEvaluator",
    "ReadinessEvidence",
    "ReadinessLevel",
    "ReadinessStatus",
    "ReadinessTier",
    "ReadinessValidationError",
    "REQUIRED_SECURITY_GATE_IDS",
    "SecurityGateDecision",
    "SupportabilityDecision",
    "SupportabilityStatus",
    "SupportabilityEvaluator",
    "SqlAlchemyReadinessStore",
    "default_capability_registry",
    "evidence_class_at_least",
    "validate_digest",
    "validate_evidence_reference",
    "validate_revision",
    "validate_scope_segment",
]
