"""Read-only GitHub, Vercel, and Supabase connector contracts."""

from __future__ import annotations

from .adapters import ConnectorRegistry, FixtureTransport
from .base import (
    ConnectorAccessError,
    FixtureReadOnlyConnector,
    GitHubReadOnlyConnector,
    ReadOnlyConnector,
    SupabaseReadOnlyConnector,
    VercelReadOnlyConnector,
    build_fixture_connector,
)
from .contracts import (
    CheckResult,
    ConnectorAdapter,
    CredentialContext,
    NormalizedConnectorResult,
    ProviderAssetObservation,
    ProviderName,
    ReadOnlyRequest,
)
from .credential_vault import (
    BootstrapStep,
    CredentialVaultError,
    Ed25519KeyService,
    EncryptedCredentialVault,
    FileMasterKeyProvider,
    ManualOnboardingInstructions,
    MasterKeyProvider,
    OffboardingReceipt,
    RestrictedBootstrapPlan,
    VaultCredentialProvider,
    VaultCredentialRecord,
    VaultCredentialStatus,
)
from .credentials import CredentialLifecycleError, CredentialRegistry
from .linux_ssh import (
    ApplicationRootVerification,
    BoundedLimits,
    CapabilityClass,
    CommandRegistry,
    ConnectionProbe,
    FilesystemMetadataRead,
    HostInventory,
    HostKeyVerificationError,
    InMemoryOperationLedger,
    InventoryRecord,
    KnownHostsStore,
    LinuxCredentialMetadata,
    LinuxCredentialRegistry,
    LinuxInventorySnapshot,
    LinuxSSHClient,
    LinuxSSHError,
    LinuxTarget,
    LiveReceiptAttestor,
    NetworkBindingRead,
    OpenSSHProcessRunner,
    OperationKind,
    OperationRejected,
    OperationStatus,
    RemoteExecutionResult,
    ResolvedCredential,
    RootControlledLiveReceiptAttestor,
    RuntimeMetadataRead,
    SafeFileRead,
    ServiceMetadataRead,
    SqliteOperationLedger,
    StorageMetadataRead,
    TargetValidationError,
    WebServerMetadataRead,
)
from .linux_ssh import (
    CredentialBoundaryError as LinuxCredentialBoundaryError,
)
from .linux_ssh import (
    CredentialProvider as LinuxCredentialProvider,
)
from .linux_ssh import (
    CredentialStatus as LinuxCredentialStatus,
)
from .live_inventory_attestor import (
    ATTESTOR_EVIDENCE_PATH,
    ATTESTOR_POLICY_PATH,
    ATTESTOR_PRIVATE_KEY_PATH,
    ATTESTOR_REPLAY_LEDGER_PATH,
    AttestorError,
    AttestorPolicy,
    InMemoryTrustedOperationEvidenceStore,
    JsonTrustedOperationEvidenceStore,
    RootBinding,
    RootControlledLiveInventoryAttestor,
    SqliteAttestorReplayLedger,
    TrustedOperationEvidence,
    UnixSocketAttestorServer,
    load_policy,
    load_signing_key,
)
from .profiles import (
    GITHUB_PROFILE,
    PROVIDER_PROFILES,
    SUPABASE_PROFILE,
    VERCEL_PROFILE,
    provider_profile,
    validate_scopes,
)
from .providers import PROVIDER_SPECS, ProviderConfigurationError, get_provider_spec
from .transport import ProviderTransportError, UnavailableTransport
from .types import (
    ConnectorHealth,
    CredentialMetadata,
    InventoryAsset,
    OwnershipResult,
    OwnershipTarget,
    PermissionResult,
    ProviderSnapshot,
    ProviderSpec,
    RemoteRecord,
)

__all__ = [
    "CheckResult",
    "ApplicationRootVerification",
    "BoundedLimits",
    "CapabilityClass",
    "CommandRegistry",
    "ConnectionProbe",
    "ConnectorAdapter",
    "ConnectorAccessError",
    "ConnectorHealth",
    "ConnectorRegistry",
    "CredentialContext",
    "CredentialLifecycleError",
    "CredentialVaultError",
    "BootstrapStep",
    "LinuxCredentialBoundaryError",
    "LinuxCredentialProvider",
    "LinuxCredentialStatus",
    "CredentialMetadata",
    "CredentialRegistry",
    "Ed25519KeyService",
    "EncryptedCredentialVault",
    "FileMasterKeyProvider",
    "FixtureTransport",
    "FixtureReadOnlyConnector",
    "GITHUB_PROFILE",
    "GitHubReadOnlyConnector",
    "InventoryAsset",
    "InventoryRecord",
    "KnownHostsStore",
    "LinuxCredentialMetadata",
    "LinuxCredentialRegistry",
    "LinuxInventorySnapshot",
    "LinuxSSHClient",
    "LinuxSSHError",
    "LinuxTarget",
    "LiveReceiptAttestor",
    "NormalizedConnectorResult",
    "NetworkBindingRead",
    "OwnershipResult",
    "OwnershipTarget",
    "PermissionResult",
    "PROVIDER_PROFILES",
    "PROVIDER_SPECS",
    "ProviderConfigurationError",
    "ProviderAssetObservation",
    "ProviderName",
    "ProviderSnapshot",
    "ProviderSpec",
    "ProviderTransportError",
    "ReadOnlyRequest",
    "ReadOnlyConnector",
    "ManualOnboardingInstructions",
    "MasterKeyProvider",
    "OffboardingReceipt",
    "RemoteExecutionResult",
    "ResolvedCredential",
    "RemoteRecord",
    "RestrictedBootstrapPlan",
    "SupabaseReadOnlyConnector",
    "SUPABASE_PROFILE",
    "UnavailableTransport",
    "VERCEL_PROFILE",
    "VercelReadOnlyConnector",
    "FilesystemMetadataRead",
    "HostInventory",
    "HostKeyVerificationError",
    "InMemoryOperationLedger",
    "OpenSSHProcessRunner",
    "RootControlledLiveReceiptAttestor",
    "OperationKind",
    "OperationRejected",
    "OperationStatus",
    "RuntimeMetadataRead",
    "SafeFileRead",
    "ServiceMetadataRead",
    "SqliteOperationLedger",
    "StorageMetadataRead",
    "TargetValidationError",
    "VaultCredentialProvider",
    "VaultCredentialRecord",
    "VaultCredentialStatus",
    "WebServerMetadataRead",
    "ATTESTOR_EVIDENCE_PATH",
    "ATTESTOR_POLICY_PATH",
    "ATTESTOR_PRIVATE_KEY_PATH",
    "ATTESTOR_REPLAY_LEDGER_PATH",
    "AttestorError",
    "AttestorPolicy",
    "InMemoryTrustedOperationEvidenceStore",
    "JsonTrustedOperationEvidenceStore",
    "RootBinding",
    "RootControlledLiveInventoryAttestor",
    "SqliteAttestorReplayLedger",
    "TrustedOperationEvidence",
    "UnixSocketAttestorServer",
    "load_policy",
    "load_signing_key",
    "build_fixture_connector",
    "get_provider_spec",
    "provider_profile",
    "validate_scopes",
]
