"""Read-only GitHub, Vercel, and Supabase connector contracts."""

from __future__ import annotations

from .adapters import ConnectorRegistry, FixtureTransport
from .base import (
    ConnectorAccessError,
    FixtureReadOnlyConnector,
    GitHubReadOnlyConnector,
    ReadOnlyConnector,
    SupabaseReadOnlyConnector,
    VercelReadOnlyConnector,
    build_fixture_connector,
)
from .contracts import (
    CheckResult,
    ConnectorAdapter,
    CredentialContext,
    NormalizedConnectorResult,
    ProviderAssetObservation,
    ProviderName,
    ReadOnlyRequest,
)
from .credentials import CredentialLifecycleError, CredentialRegistry
from .linux_ssh import (
    ApplicationRootVerification,
    BoundedLimits,
    CapabilityClass,
    CommandRegistry,
    ConnectionProbe,
    FilesystemMetadataRead,
    HostInventory,
    HostKeyVerificationError,
    InMemoryOperationLedger,
    InventoryRecord,
    KnownHostsStore,
    LinuxCredentialMetadata,
    LinuxCredentialRegistry,
    LinuxInventorySnapshot,
    LinuxSSHClient,
    LinuxSSHError,
    LinuxTarget,
    NetworkBindingRead,
    OpenSSHProcessRunner,
    OperationKind,
    OperationRejected,
    OperationStatus,
    RemoteExecutionResult,
    ResolvedCredential,
    RuntimeMetadataRead,
    SafeFileRead,
    ServiceMetadataRead,
    StorageMetadataRead,
    TargetValidationError,
    WebServerMetadataRead,
)
from .linux_ssh import (
    CredentialBoundaryError as LinuxCredentialBoundaryError,
)
from .linux_ssh import (
    CredentialProvider as LinuxCredentialProvider,
)
from .linux_ssh import (
    CredentialStatus as LinuxCredentialStatus,
)
from .profiles import (
    GITHUB_PROFILE,
    PROVIDER_PROFILES,
    SUPABASE_PROFILE,
    VERCEL_PROFILE,
    provider_profile,
    validate_scopes,
)
from .providers import PROVIDER_SPECS, ProviderConfigurationError, get_provider_spec
from .transport import ProviderTransportError, UnavailableTransport
from .types import (
    ConnectorHealth,
    CredentialMetadata,
    InventoryAsset,
    OwnershipResult,
    OwnershipTarget,
    PermissionResult,
    ProviderSnapshot,
    ProviderSpec,
    RemoteRecord,
)

__all__ = [
    "CheckResult",
    "ApplicationRootVerification",
    "BoundedLimits",
    "CapabilityClass",
    "CommandRegistry",
    "ConnectionProbe",
    "ConnectorAdapter",
    "ConnectorAccessError",
    "ConnectorHealth",
    "ConnectorRegistry",
    "CredentialContext",
    "CredentialLifecycleError",
    "LinuxCredentialBoundaryError",
    "LinuxCredentialProvider",
    "LinuxCredentialStatus",
    "CredentialMetadata",
    "CredentialRegistry",
    "FixtureTransport",
    "FixtureReadOnlyConnector",
    "GITHUB_PROFILE",
    "GitHubReadOnlyConnector",
    "InventoryAsset",
    "InventoryRecord",
    "KnownHostsStore",
    "LinuxCredentialMetadata",
    "LinuxCredentialRegistry",
    "LinuxInventorySnapshot",
    "LinuxSSHClient",
    "LinuxSSHError",
    "LinuxTarget",
    "NormalizedConnectorResult",
    "NetworkBindingRead",
    "OwnershipResult",
    "OwnershipTarget",
    "PermissionResult",
    "PROVIDER_PROFILES",
    "PROVIDER_SPECS",
    "ProviderConfigurationError",
    "ProviderAssetObservation",
    "ProviderName",
    "ProviderSnapshot",
    "ProviderSpec",
    "ProviderTransportError",
    "ReadOnlyRequest",
    "ReadOnlyConnector",
    "RemoteExecutionResult",
    "ResolvedCredential",
    "RemoteRecord",
    "SupabaseReadOnlyConnector",
    "SUPABASE_PROFILE",
    "UnavailableTransport",
    "VERCEL_PROFILE",
    "VercelReadOnlyConnector",
    "FilesystemMetadataRead",
    "HostInventory",
    "HostKeyVerificationError",
    "InMemoryOperationLedger",
    "OpenSSHProcessRunner",
    "OperationKind",
    "OperationRejected",
    "OperationStatus",
    "RuntimeMetadataRead",
    "SafeFileRead",
    "ServiceMetadataRead",
    "StorageMetadataRead",
    "TargetValidationError",
    "WebServerMetadataRead",
    "build_fixture_connector",
    "get_provider_spec",
    "provider_profile",
    "validate_scopes",
]

